# Индивидуальное задание

Дана целочисленная квадратная матрица. Определить: сумму элементов в тех столбцах, которые не содержат отрицательных элементов; минимум среди модулей элементов диагоналей, параллельных побочной диагонали матрицы.

In [2]:
import numpy as np

In [8]:
n = int(input("Enter the size of the matrix: "))

Enter the size of the matrix: 3


In [9]:
matrix = np.random.randint(-20, 100, (n, n))
print(matrix)

[[ -4  95  52]
 [ 96  31  54]
 [-11  64  87]]


1. Сумма элементов в тех столбцах, которые не содержат отрицательных элементов

In [10]:
print(matrix.min(axis=0) > 0)

[False  True  True]


In [11]:
print(matrix[:, matrix.min(axis=0) > 0])

[[95 52]
 [31 54]
 [64 87]]


In [12]:
summa = np.sum(matrix[:, matrix.min(axis=0) > 0])
print(summa)

383


2. Минимум среди сумм модулей элементов диагоналей, параллельных побочной диагонали матрицы

In [13]:
import numpy as np 

In [14]:
n = int(input("Enter the size of the matrix: "))

Enter the size of the matrix: 6


In [15]:
matrix = np.random.randint(-20, 300, (n, n))
matrix = np.absolute(matrix)
print(matrix)

[[110 206 179 293 249 125]
 [235 182 227 114 142  14]
 [ 76 190  52 298 294 215]
 [258  28  75 224 226 172]
 [134 107 257  81 275 233]
 [ 88 199 236 122 239 188]]


In [16]:
min_sum = min([np.fliplr(matrix).trace(offset=i) for i in range(-(n-1), n)])
print(min_sum)

110
